name: C++ CI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install g++
      run: sudo apt-get install -y g++

    - name: Compile C++ code
      run: g++ sum_of_natural_numbers.cpp -o sum

    - name: Run compiled program
      run: ./sum
